defaults: &defaults
  cognitive_subscription_key: "It`s secret"

development:
  <<: *defaults
  database:
    pool: 5
    database: 'test_app_dev'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'

test:
  <<: *defaults
  database:
    pool: 5
    database: 'test_app_test'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'
